AWSTemplateFormatVersion: "2010-09-09"
Description: CodeDeploy ECS Application & Deployment Group

Parameters:
  AppName:
    Type: String
  LabTag:
    Type: String
  ClusterName:
    Type: String
  ServiceName:
    Type: String
  TargetGroup1:
    Type: String
  TargetGroup2:
    Type: String
  ListenerArn:
    Type: String

Resources:
  # CodeDeploy IAM Role
  ECSCodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-codedeploy-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeDeployECSInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:*
                  - elasticloadbalancing:*
                  - cloudwatch:*
                  - sns:*
                  - s3:*
                  - lambda:InvokeFunction
                  - iam:PassRole
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-codedeploy-role
        - Key: Lab
          Value: !Ref LabTag

  # CodeDeploy Application
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub ${AppName}-codedeploy-app
      ComputePlatform: ECS

  # Deployment Group
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: !Sub ${AppName}-codedeploy-group
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      ServiceRoleArn: !GetAtt ECSCodeDeployRole.Arn
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 3
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - Name: !Ref TargetGroup1
              - Name: !Ref TargetGroup2
            ProdTrafficRoute:
              ListenerArns:
                - !Ref ListenerArn
      ECSServices:
        - ClusterName: !Ref ClusterName
          ServiceName: !Ref ServiceName

Outputs:
  CodeDeployAppName:
    Description: "CodeDeploy Application for ECS Blue/Green"
    Value: !Ref CodeDeployApp
    Export:
      Name: !Sub ${AppName}-codedeploy-app

  CodeDeployDeploymentGroupName:
    Description: "Deployment Group for ECS Blue/Green"
    Value: !Ref CodeDeployDeploymentGroup
    Export:
      Name: !Sub ${AppName}-codedeploy-group
