version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          ContainerName: taskly-todo-container
          ContainerPort: 8082
